### ISSUE TITLE
Save Classifier

### ISSUE THREAD

**Issue by JT17** [EasonLiao/CudaTree#2]
Hi so is there any way to train a classifier and then save it? I might just be missing something obvious but currently I try to use cPickle and dump the trained classifier to a file. When I reload the classifier, however, it does not have the kernels initialized. I saw in the latest commit that kernels were not picklable but is there some other way to store the classifier? Having to retrain all the time is quite time consuming.

Thanks!

**Comment by EasonLiao** [comment]
Hi I guess you are correct. Currently when you reload the classifier, it will only restore the constructed trees but not the compiled kernels. 

Probably I'll fix it later but one thing you could try is that you can just do something similar with hybridforest does. You restore the forest from file, and construct a new random forest with same data types but just with one tree. Then add the trees from the reloaded random forest to the new trained one.  Since the new trained random forest has all the kernels compiled, it should work.

**Comment by JT17** [comment]
How do you add the trees from the reloaded random forest to the new trained one?

**Comment by EasonLiao** [comment]
@JT17 If I remember correct. The RandomForestClassifier has a field called  `_trees`. It stores a list of trained random forest trees. You can just do something like : 

```
forest_for_one_tree._trees.extend(forest_from_file._trees)
```

Sorry I don't have GPU now for testing. But this should work.

**Comment by JT17** [comment]
Okay so that worked for reloading a trained classifier. However, compared to a CPU classifier, the GPU trained classifier was almost twice as slow. Is that expected? Is there a way to improve performance?

**Comment by EasonLiao** [comment]
@JT17  Here CPU classifier you mean scikit-learn random forest classifier? 

Yeah, GPU classifier was way faster than scikit-learn classifier before. But later scikit-learn optimized their implementation so it might be faster than GPU classifier now. Also, it depends how powerfull you GPU is.

So my suggestion is : If you find scikit-learn is faster than CudaTree, just use scikit-learn or hybrid version. I can't come up any ideas can make CudaTree faster than scikit-learn in simple ways.

**Comment by JT17** [comment]
Okay thanks. One last question. I have scaled image size as input to the classifier and as images get bigger, the CPU performs better and better compared to the GPU. I expected it to be the opposite, and that while the CPU may outperform on smaller inputs the GPU should gain an advantage as images get bigger. Can you think of why this is the case?
