### ISSUE TITLE
TypeError: 'numpy.uint32' does not have the buffer interface

### ISSUE THREAD

**Issue by StevenLOL** [EasonLiao/CudaTree#3]
Install from pip / source code all give this error:

driver.memcpy_htod(const_stride, np.uint32(self.stride))

when calling

forest.fit(x_train, y_train, bfs_threshold = 4196) # from the example in readme

Running ubuntu 14.04,64bits, nvidia-331

**Comment by EasonLiao** [comment]
Could you tell me which version of numpy are you using? I suspect it's because the numpy version is too old.

**Comment by StevenLOL** [comment]
1.8.1

**Comment by HarveyLiuFly** [comment]
I have encoutered the same issue. help needed.

**Comment by wideblue** [comment]
Got the same error when running benchmark_all.py.  

numpy : 1.9.0 
on OS X 10.9.4

**Comment by EasonLiao** [comment]
Sorry, I never encountered this problem on my machine, give me some time, I'll try if I can figure out...

**Comment by 0x0all** [comment]
ubuntu-64 14.04, nvidia driver 340.46, 
python 2.7.6, GCC 4.8.2, numpy 1.8.2

TypeError: 'numpy.uint32' does not have the buffer interface

**Comment by EasonLiao** [comment]
Hi everyone,

Sorry I've decided not to maintain CudaTree anymore since in scikit-learn made a significant improvements on its random forest implementation this year, so I suggest you should use scikit-learn or WiseRF instead.

**Comment by 0x0all** [comment]
Thank you

**Comment by EasonLiao** [comment]
thanks @palicand ! This issues has been fixed.
